"""votes posts

Revision ID: 1e6a74419186
Revises: a80d5a552ed1
Create Date: 2023-01-24 21:37:01.931202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6a74419186'
down_revision = 'a80d5a552ed1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('vote', sa.Integer(), nullable=False))
    op.drop_column('votes', 'dir')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('dir', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('votes', 'vote')
    # ### end Alembic commands ###
