"""plz work

Revision ID: 326c51a422a8
Revises: 97b3faa052e0
Create Date: 2023-01-23 22:35:39.970811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326c51a422a8'
down_revision = '97b3faa052e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
