"""fuuuuuuuuuuuuuuuuu

Revision ID: 371944230f39
Revises: 326c51a422a8
Create Date: 2023-01-23 22:46:42.718943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371944230f39'
down_revision = '326c51a422a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
