"""empty message

Revision ID: 3abfbc2d035b
Revises: 7e78c68741be
Create Date: 2023-02-02 22:59:47.999298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abfbc2d035b'
down_revision = '7e78c68741be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
