"""added stuff

Revision ID: 4ccc139ad143
Revises: 9ce70a3eb1e9
Create Date: 2023-02-03 17:41:16.926845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccc139ad143'
down_revision = '9ce70a3eb1e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'votes', ['likes'], ['direction'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###
