"""empty message

Revision ID: 9ce70a3eb1e9
Revises: 7861c7935712
Create Date: 2023-02-03 14:54:32.566706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce70a3eb1e9'
down_revision = '7861c7935712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('direction', sa.Integer(), nullable=False))
    op.drop_column('votes', 'dir')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('dir', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('votes', 'direction')
    # ### end Alembic commands ###
