"""plz work 1

Revision ID: a80d5a552ed1
Revises: 371944230f39
Create Date: 2023-01-23 22:51:59.179964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80d5a552ed1'
down_revision = '371944230f39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
